### ISSUE TITLE
Failes to load on ThinkPad T580

### ISSUE THREAD

**Issue by Pascal3366** [linux-thinkpad/tp_smapi#36]
tp_smami fails to load on ThinkPad T580, running with Arch Linux on Kernel 5.1.4

[   11.918246] thinkpad_ec: thinkpad_ec_request_row: arg0 rejected: (0x01:0x00)->0x00
[   11.918248] thinkpad_ec: thinkpad_ec_read_row: failed requesting row: (0x01:0x00)->0xfffffffb
[   11.918288] thinkpad_ec: initial ec test failed
[   12.598834] thinkpad_acpi: ThinkPad ACPI Extras v0.26
[   12.598835] thinkpad_acpi: http://ibm-acpi.sf.net/
[   12.598837] thinkpad_acpi: ThinkPad BIOS N27ET34W (1.20 ), EC unknown
[   12.598838] thinkpad_acpi: Lenovo ThinkPad T580, model 20LAS2MR07
[   12.604340] thinkpad_acpi: radio switch found; radios are enabled
[   12.604667] thinkpad_acpi: This ThinkPad has standard ACPI backlight brightness control, supported by the ACPI video driver
[   12.604668] thinkpad_acpi: Disabling thinkpad-acpi brightness events by default...
[   12.630470] thinkpad_acpi: Standard ACPI backlight interface available, not loading native one
[   12.717375] thinkpad_acpi: battery 1 registered (start 0, stop 100)
[   12.717441] input: ThinkPad Extra Buttons as /devices/platform/thinkpad_acpi/input/input7
[   12.836149] thinkpad_acpi: battery 2 registered (start 0, stop 100)
[   14.004244] thinkpad_ec: thinkpad_ec_request_row: arg0 rejected: (0x01:0x00)->0x00
[   14.004247] thinkpad_ec: thinkpad_ec_read_row: failed requesting row: (0x01:0x00)->0xfffffffb
[   14.004317] thinkpad_ec: initial ec test failed

**Comment by ivohulsman** [comment]
I have the exact same behavior on a T490 / Arch.

**Comment by adrianf0** [comment]
I have the same problem with T480 on Ubuntu 18.04 LTS.

**Comment by lukasmichel** [comment]
I have the same problem on an L580. What info can I provide to help fixing this issue?

**Comment by schultzern** [comment]
I have the same problem as well on my T580 running kernel `5.4.11-arch1-1`

**Comment by lokedhs** [comment]
I started having this problem a few days ago. Uninstalling `tp_smapi` fixes the problem obviously. But what's more interesting is that if I reinstall it I can successfully reboot the ocmpute multiple times without any issue. But turing it off and then booting it a day later will cause the problem to come back.

**Comment by gergoerdi** [comment]
I am seeing this problem now on Linux 5.4.0-37, as packaged for Ubuntu 20.04, on a Thinkpad T480s. It worked with Ubuntu 18.04, running on Linux 4.15.0-106.

What's interesting is that I have tried downgrading `tp_smapi` from 0.43 (as shipped with Ubuntu 20.04) to 0.42 (as shipped with Ubuntu 18.04), and that still gives the same error message. So the same version of `tp_smapi` that used to work on Ubuntu 18.04 now fails with the `intial ec test failed` message.

Does this suggest that the root cause is a change in the main Linux kernel somewhere between 4.15.0 and 5.4.0?

**Comment by evgeni** [comment]
Anything newer than SandyBridge (X220, T420, etc) is not supported (and won't be), sorry.
