### ISSUE TITLE
Build failure, kernels 5.4 and 5.5

### ISSUE THREAD

**Issue by robinpaulson** [linux-thinkpad/tp_smapi#38]
When I install the latest mainline Linux kernel from Ubuntu (from https://kernel.ubuntu.com/~kernel-ppa/mainline/), I get these errors as it builds the various dkms modules:
make -j4 KERNELRELEASE=5.5.0-050500-generic -C /lib/modules/5.5.0-050500-generic/build M=/var/lib/dkms/tp_smapi/0.43/build HDAPS=1...(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-5.5.0-050500-generic is not supported
Error! Bad return status for module build on kernel: 5.5.0-050500-generic (x86_64)

It worked previously, going back many kernel versions, until 5.3, everything since then has not built.

See attached for the build log.
[make.log](https://github.com/linux-thinkpad/tp_smapi/files/4119647/make.log)

This is for Ubuntu 18.04, Thinkpad T420

I get this for another dkms module, acpi-call as well, but not hdaps. I'm guessing it might be a more general kernel problem, but thought I'd mention it here too. I'm not keen on approaching kernel devs directly, LKML is a scary place.

**Comment by evgeni** [comment]
sorry, can't repro
