### ISSUE TITLE
modprobe: ERROR: could not insert 'tp_smapi': No such device or address

### ISSUE THREAD

**Issue by dchmelik** [linux-thinkpad/tp_smapi#44]
On a ThinkPad T500 I get 'modprobe: ERROR: could not insert 'tp_smapi': No such device or address'.  It loads thinkpad_ec fine.  It has LibreBoot.

**Comment by evgeni** [comment]
Does LibreBoot in any way affect the EC? If so, this sounds like a bug there. The 500 series should "just work".

**Comment by dchmelik** [comment]
> Does LibreBoot in any way affect the EC?

I don't know what EC is, but I used to be able to set battery charge thresholds in older Linux kernels.

**Comment by evgeni** [comment]
The EC is the piece of hardware/firmware that's responsible for charge thresholds and other out of band things while your OS is running (https://www.thinkwiki.org/wiki/Embedded_Controller_Firmware), it's usually updated together with the bios.

Did the thresholds work with the identical version of LibreBoot on older kernels? Do they still work if you boot the old kernel?
Which version works, which does not?

**Comment by evgeni** [comment]
According to https://libreboot.org/docs/hardware/t500.html LB should not affect the EC, interesting 🤔

**Comment by dchmelik** [comment]
> Did the thresholds work with the identical version of LibreBoot on older kernels?

They worked with it on some Linux kernel v4, which may be mostly discontinued; my OS (Slackware GNU/Linux) distributes v5 since earlier this year, so I'm not planning to reinstall v4.  However, my LibreBoot may also be old--likely previous stable version from about 2017, which though EC worked with that and Linux kernel v4, don't know it does with newer.  LibreBoot installation instructions aren't very helpful for non-experts who don't want to disassemble their laptop, so I'm kind of stuck on upgrading to their new stable version (even though I don't have to disassemble it again, it's going through many pages & pages just to find a few and probably undocumented commands).

**Comment by dchmelik** [comment]
I did get around to trying old kernels, but now it doesn't work on those either.  I'd guess it's a hardware problem, unless TLP or tp_smapi itself changed.
