### ISSUE TITLE
Build failure kernel 6.4

### ISSUE THREAD

**Issue by coogor** [linux-thinkpad/tp_smapi#49]
Hi,
the program fails to build for current Kernel:

[   69s] + make KVER=6.4.3-1-default KSRC=/usr/src/linux KBUILD=/usr/src/linux-obj/x86_64/default M=/home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/obj/default HDAPS=1
[   69s] make -C /usr/src/linux-obj/x86_64/default M=/home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default O=/usr/src/linux-obj/x86_64/default modules
[   69s] make[1]: Entering directory '/usr/src/linux-6.4.3-1-obj/x86_64/default'
[   71s]   CC [M]  /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.o
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c:94:42: **error: macro "DEFINE_SEMAPHORE" requires 2 arguments, but only 1 given**
[   71s]    94 | static DEFINE_SEMAPHORE(thinkpad_ec_mutex);
[   71s]       |                                          ^
[   71s] In file included from /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c:45:
[   71s] /usr/src/linux-6.4.3-1/include/linux/semaphore.h:34: note: macro "DEFINE_SEMAPHORE" defined here
[   71s]    34 | #define DEFINE_SEMAPHORE(_name, _n)     \
[   71s]       | 
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c:94:8: error: type defaults to 'int' in declaration of 'DEFINE_SEMAPHORE' [-Werror=implicit-int]
[   71s]    94 | static DEFINE_SEMAPHORE(thinkpad_ec_mutex);
[   71s]       |        ^~~~~~~~~~~~~~~~
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c: In function 'thinkpad_ec_lock':
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c:112:35: error: 'thinkpad_ec_mutex' undeclared (first use in this function); did you mean 'thinkpad_ec_lock'?
[   71s]   112 |         ret = down_interruptible(&thinkpad_ec_mutex);
[   71s]       |                                   ^~~~~~~~~~~~~~~~~
[   71s]       |                                   thinkpad_ec_lock
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c:112:35: note: each undeclared identifier is reported only once for each function it appears in
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c: In function 'thinkpad_ec_try_lock':
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c:126:30: error: 'thinkpad_ec_mutex' undeclared (first use in this function); did you mean 'thinkpad_ec_lock'?
[   71s]   126 |         return down_trylock(&thinkpad_ec_mutex);
[   71s]       |                              ^~~~~~~~~~~~~~~~~
[   71s]       |                              thinkpad_ec_lock
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c: In function 'thinkpad_ec_unlock':
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c:138:13: error: 'thinkpad_ec_mutex' undeclared (first use in this function); did you mean 'thinkpad_ec_lock'?
[   71s]   138 |         up(&thinkpad_ec_mutex);
[   71s]       |             ^~~~~~~~~~~~~~~~~
[   71s]       |             thinkpad_ec_lock
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c: In function 'thinkpad_ec_try_lock':
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c:127:1: error: control reaches end of non-void function [-Werror=return-type]
[   71s]   127 | }
[   71s]       | ^
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c: At top level:
[   71s] /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.c:94:8: warning: 'DEFINE_SEMAPHORE' defined but not used [-Wunused-variable]
[   71s]    94 | static DEFINE_SEMAPHORE(thinkpad_ec_mutex);
[   71s]       |        ^~~~~~~~~~~~~~~~
[   71s] cc1: some warnings being treated as errors
[   71s] make[2]: *** [/usr/src/linux-6.4.3-1/scripts/Makefile.build:253: /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default/thinkpad_ec.o] Error 1
[   71s] make[1]: *** [../../../linux-6.4.3-1/Makefile:2043: /home/abuild/rpmbuild/BUILD/tp_smapi-0.43/obj/default] Error 2
[   71s] make[1]: Leaving directory '/usr/src/linux-6.4.3-1-obj/x86_64/default'
[   71s] make: *** [Makefile:46: modules] Error 2
[   71s] error: Bad exit status from /var/tmp/rpm-tmp.flW3aw (%build)

**Comment by evgeni** [comment]
this is fixed in https://github.com/linux-thinkpad/tp_smapi/commit/0c3398b1acf2a2cabd9cee91dc3fe3d35805fa8b
