### ISSUE TITLE
Fedora 38 still on 0.43

### ISSUE THREAD

**Issue by schumischumi** [linux-thinkpad/tp_smapi#59]
Hi,
could you update the package for fedora 38 to 0.44?

Name         : akmod-tp_smapi
Version      : 0.43
Release      : 12.fc38
Architektur  : x86_64
Größe        : 56 k
Quelle       : tp_smapi-kmod-0.43-12.fc38.src.rpm
Paketquelle  : @System
Aus Paketque : tlp
Zusammenfass : Akmod package for tp_smapi kernel module(s)
URL          : http://www.thinkwiki.org/wiki/Tp_smapi
Lizenz       : GPL
Beschreibung : This package provides the akmod package for the tp_smapi kernel modules.

If you don't manage the package can you point me in the right direction who to ask?

Thank you very much!

**Comment by evgeni** [comment]
I don't manage that package and have no idea who does, sorry.
