### ISSUE TITLE
cannot build on kernel 6.7.10-200.fc39.x86_64

### ISSUE THREAD

**Issue by yusi1** [linux-thinkpad/tp_smapi#62]
Hi, I'm trying to build this on Fedora with the 6.7.10-200.fc39.x86_64 kernel but I get this:
```
make: *** No rule to make target '/lib/modules/6.7.10-200.fc39.x86_64/build', needed by 'modules'.  Stop.
```
How do I fix it? Thanks.

**Comment by evgeni** [comment]
Do you have the matching kernel headers installed?

**Comment by yusi1** [comment]
> Do you have the matching kernel headers installed?

no

**Comment by yusi1** [comment]
Updating the kernel fixed the issue, the headers were the wrong version. Thank you

**Comment by evgeni** [comment]
Cool. Glad we could fix it so easily :)
