### ISSUE TITLE
Platform/smapi/* is not created on T410

### ISSUE THREAD

**Issue by ktnlikeasmallcat** [linux-thinkpad/tp_smapi#63]
I installed tp_smapi-dkms from xbps on void linux and rebooted, but `/sys/devices/platform/smapi` does not appear, do I create these files? What Might cause this?
Thank you in advance.
```
ls /sys/devices/platform

acpi-cpufreq 
coretemp.0 
dock.0 
dock.1 
'Fixed MDIO bus.0' 
i8042 
microcode 
pcspkr 
PNPC0D:00 
PNPC0E:00 
PNPC14:01 
power 
reg-dummy 
regulatory.0 
serial8250 
thinkpad_acpi 
thinkpsd_hwmon 
uevent

**Comment by evgeni** [comment]
Is the tp_smapi module loaded? It doesn't autoload.

**Comment by ktnlikeasmallcat** [comment]
nailed it thanks!

**Comment by evgeni** [comment]
So we can close this?
