### ISSUE TITLE
Documentation: a 'note' leads, indirectly, to an important but missing webpage

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linux-thinkpad/tp_smapi#67]
[This admirable piece of documentation](https://linrunner.de/tlp/faq/battery.html) contains the following.

![image](https://github.com/user-attachments/assets/8b6a0acc-15b7-41d5-b600-cf84cfc067d3)

The link leads to an extant webpage, but that page itself links to an ostensible list of ThinkPads that do automatic battery threshold setting; and _the page containing that list does not exist_.

I could not determine whether the contents of the missing page exist elsewhere. Possibly that content exists somewhere within the huge discussion thread that is at issue!

**Comment by evgeni** [comment]
That page is not owned by me.

Cc @linrunner?

**Comment by linrunner** [comment]
@LinuxOnTheDesktop I'm sorry, I don't know any other source for the list and at the same time I doubt that the statement also applies to current thinkpads, the topic is 11 years old after all.

**Comment by LinuxOnTheDesktop** [comment]
@linrunner : thanks.

> I doubt that the statement also applies to current thinkpads, the topic is 11 years old after all

Perhaps the documentation ought to be modified to reflect that fact.

**Comment by linrunner** [comment]
@LinuxOnTheDesktop Is noted. For the 1.7 release, the Battery FAQ has to be cleared out a lot anyway.

@evgeni thanks for the hint. Can be closed.
