### ISSUE TITLE
Error Build with Kernel 6.10.4

### ISSUE THREAD

**Issue by jreo** [linux-thinkpad/tp_smapi#68]
Building module:
Cleaning build area...
make -j6 KERNELRELEASE=6.10.4-061004-generic -C /lib/modules/6.10.4-061004-generic/build M=/var/lib/dkms/tp_smapi/0.44/build HDAPS=1...(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-6.10.4-061004-generic is not supported
Error! Bad return status for module build on kernel: 6.10.4-061004-generic (x86_64)
Consult /var/lib/dkms/tp_smapi/0.44/build/make.log for more information.
dkms autoinstall on 6.10.4-061004-generic/x86_64 failed for fwts-efi-runtime-dkms(10) tp_smapi(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
 * dkms: autoinstall for kernel 6.10.4-061004-generic
   ...fail!

**Comment by evgeni** [comment]
"kernel package linux-headers-6.10.4-061004-generic is not supported" doesn't sound like an issue with the tp smapi code, but rather your setup?

**Comment by jreo** [comment]
I'm sorry, for sure! You're writing. After investigating, I found that the question was gg-14. Fixed. The code was built correctly. Thanks.
